# 
#  # (description)
#  # (description)

#  # (description)
initialized: true

app:
  name: "FastAPI-Vue-Admin"
  version: "1.0.7"
  host: "0.0.0.0"
  port: 9090
  env: "dev"
  api_prefix: "/api"
  reload: true
  api_status_enabled: true

jwt:
  algorithm: "HS256"
  secret_key: "395219dd62c071413d7e451401141ac8a51eeb21d52d8b2b23cc24029f1456ef"
  salt: "fastapi-vue-admin"
  expire_minutes: 1440
  redis_expire_minutes: 30

database:
  engine: "mysql"
  host: "127.0.0.1"
  port: 3307
  username: "root"
  password: "123456"
  database: "fva_db"
  pool_size: 10
  pool_timeout: 30
  echo: false
  timezone: "Asia/Shanghai"
  charset: "utf8mb4"

redis:
  mode: "server"
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 1
  max_connections: 10
  socket_timeout: 5
  retry_on_timeout: true
